# Generated by Django 5.0.4 on 2024-05-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoFile', models.FileField(default='', upload_to='')),
                ('audioFile', models.FileField(upload_to='')),
            ],
        ),
    ]
